// 此文件由脚本自动生成，请勿手动修改
// Auto-generated by scripts/generateRoutes.js

import { createRouter, createWebHistory } from 'vue-router'

// 动态导入页面组件
const Home = () => import('../Pages/Home/index.vue')

const routes = [
  {
    path: '/',
    name: 'Home',
    component: Home,
    meta: {
      title: '首页'
    }
  }
]

const router = createRouter({
  history: createWebHistory(),
  routes
})

// 路由守卫
router.beforeEach((to, from, next) => {
  // 设置页面标题
  if (to.meta.title) {
    document.title = to.meta.title
  }
  next()
})

export default router
